micronaut:
  application:
    name: gateway
  server:
    port: 8080
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
        redoc:
          paths: classpath:META-INF/swagger/views/redoc
          mapping: /redoc/**
        rapidoc:
          paths: classpath:META-INF/swagger/views/rapidoc
          mapping: /rapidoc/**
        swagger-ui:
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /swagger-ui/**
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"