micronaut:
  application:
    name: gateway
  server:
    port: 8080
    cors:
      enabled: true
    thread-selection: auto
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
        redoc:
          paths: classpath:META-INF/swagger/views/redoc
          mapping: /redoc/**
        rapidoc:
          paths: classpath:META-INF/swagger/views/rapidoc
          mapping: /rapidoc/**
        swagger-ui:
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU=
    intercept-url-map:
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"