version: "3.7"
services:
  consul:
    image: consul
    ports:
      - 8500:8500

  gateway:
    build: ./MicronautDemo/gateway
    links:
      - consul
    ports:
      - "8080:8080"
    environment:
      MICRONAUT_SERVER_HOST: gateway
      MICRONAUT_SERVER_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  products:
    build: ./MicronautDemo/products
    links:
      - consul
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: products
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  users:
    build: ./MicronautDemo/users
    links:
      - consul
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: users
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  reviews:
    build: ./MicronautDemo/reviews
    links:
      - consul
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: reviews
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  carts:
    build: ./MicronautDemo/carts
    links:
      - consul
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: carts
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  orders:
    build: ./MicronautDemo/orders
    links:
      - consul
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: orders
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    build: ./ReactDemo/nginx
    ports:
      - "80:80"

  container:
    build: ./ReactDemo/container
    ports:
      - "3000"

  login:
    build: ./ReactDemo/login
    ports:
      - "3001:3000"

  browse:
    build: ./ReactDemo/browse
    ports:
      - "3002:3000"

  signup:
    build: ./ReactDemo/signup
    ports:
      - "3003:3000"

  product:
    build: ./ReactDemo/product
    ports:
      - "3004:3000"

  productreview:
    build: ./ReactDemo/productReview
    ports:
      - "3005:3000"

  account:
    build: ./ReactDemo/account
    ports:
      - "3006:3000"

  accountorders:
    build: ./ReactDemo/accountOrders
    ports:
      - "3007:3000"

  cart:
    build: ./ReactDemo/cart
    ports:
      - "3008:3000"

  cdn:
    build: ./ReactDemo/cdn
    ports:
      - "5002:3000"

volumes:
  mongodb_data:
    labels:
      - "keep=yes"
