version: "3.7"
services:

  consul:
    image: consul
    ports:
      - 8500:8500

  gateway:
    build: ./gateway
    links:
      - consul
    ports:
      - "8080:8080"
    environment:
      MICRONAUT_SERVER_HOST: gateway
      MICRONAUT_SERVER_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  products:
    build: ./products
    links:
      - consul
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: products
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  users:
    build: ./users
    links:
      - consul
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: users
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"